[IG]
ig = fsh-generated/resources/ImplementationGuide-zw.fhir.ig.medication.json

###          PLEASE CHANGE THIS TO YOUR OWN FHIR IG TEMPLATE                      ###
###          Do this by replacing template = #zw-template below      ###
###          with template = fhir.base.template#current                           ###
###          or another FHIR template that you can use.                           ###
 
## For WHO:
template = #zw-template

# For everyone else:
#template = fhir.base.template#current

