id: zw.fhir.ig.medication
canonical: http://mohcc.gov.zw/fhir/medication
name: ZWMedication
title: Zimbabwe Medication IG
description: Zimbabwe Medication FHIR Implementation Guide covering allergies, medication requests and administration
status: draft # draft | active | retired | unknown
experimental: false
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#716 "Zimbabwe (ZWE)" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: MOH Zimbabwe
  url: http://mohcc.org.zw

dependencies:
  zw.fhir.ig.core:
    id: core
    version: current


pages:
  index.md:
    title: Home
  downloads.md:
    title: Downloads
  about.md:
    title: About


menu:
  Home:
    Summary: index.html
  Deployment:
    Downloads: downloads.html
    Artifacts: artifacts.html
  About: about.html

parameters:
  pin-canonicals: pin-multiples
